### ISSUE TITLE
Getting error when create a producer

### ISSUE THREAD

**Issue by ghost** [lab-sb/tcrepsrv-dev#12]
postgresql 16.3
openjdk 1.8
rocky 9

```
--Going to create replication slot database rdb_citus1_bdr ..
java.sql.BatchUpdateException: Batch entry 0  SELECT * FROM pg_create_logical_replication_slot('rdb_citus1_bdr', 'rdblogdec') was aborted: ERROR: could not load library "/usr/pgsql-16/lib/rdblogdec.so": /usr/pgsql-16/lib/rdblogdec.so: undefined symbol: AllocSetContextCreate  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2286)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:521)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
	at com.edslab.TCSrvCTL.createReplicationSlot(TCSrvCTL.java:1269)
	at com.edslab.TCSrvCTL.setupNode(TCSrvCTL.java:1506)
	at com.edslab.TCSrvCTL.applyOptions(TCSrvCTL.java:2409)
	at com.edslab.TCSrvCTL.applyOptions(TCSrvCTL.java:2459)
	at com.edslab.TCSrvCTL.main(TCSrvCTL.java:2501)
Caused by: org.postgresql.util.PSQLException: ERROR: could not load library "/usr/pgsql-16/lib/rdblogdec.so": /usr/pgsql-16/lib/rdblogdec.so: undefined symbol: AllocSetContextCreate
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at `org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)`
```
any advise?

**Comment by tcapturesupport** [comment]
Hello,,

you need to compile:

 rpm -ivh postgresql16-devel-16.2-1PGDG.rhel9.x86_64.rpm
  cd /tmp/rdb_decoder/
  export PATH=/usr/pgsql-16/bin/:$PATH
  make clean
  make
   sudo dnf install redhat-rpm-config
  export PATH=/usr/pgsql-16/bin/:$PATH
  cd /tmp/rdb_decoder/
  make
 make install
		/usr/bin/mkdir -p '/usr/pgsql-16/lib'
		/usr/bin/install -c -m 755  rdblogdec.so '/usr/pgsql-16/lib/'
		/usr/bin/mkdir -p '/usr/pgsql-16/lib/bitcode/rdblogdec'
		/usr/bin/mkdir -p '/usr/pgsql-16/lib/bitcode'/rdblogdec/
		/usr/bin/install -c -m 644 rdblogdec.bc '/usr/pgsql-16/lib/bitcode'/rdblogdec/./
		cd '/usr/pgsql-16/lib/bitcode' && /usr/bin/llvm-lto -thinlto -thinlto-action=thinlink -o rdblogdec.index.bc rdblogdec/rdblogdec.bc

**Comment by tcapturesupport** [comment]
source c files  are:

[tcrepsrv-dev](https://github.com/lab-sb/tcrepsrv-dev/tree/main)/[lib](https://github.com/lab-sb/tcrepsrv-dev/tree/main/lib)
/rdb_decoder/

**Comment by lab-sb** [comment]
Decoder library for PG 16 is now available under lib/16/
to use it, copy the lib : rdblogdec.so to /usr/pgsql-16/lib/
